export enum CallTarget {
  POLICE = 'POLICE',
  AMBULANCE = 'AMBULANCE',
  EURO_CALL = 'EURO_CALL',
  FIRE_BRIGADE = 'FIRE_BRIGADE',
  MOUNTAIN_CALL = 'MOUNTAIN_CALL',
  BOT_CALL = 'BOT_CALL',
  POLICE_TEST = 'POLICE_TEST',
  AMBULANCE_TEST = 'AMBULANCE_TEST',
  EURO_CALL_TEST = 'EURO_CALL_TEST',
  FIRE_BRIGADE_TEST = 'FIRE_BRIGADE_TEST',
  MOUNTAIN_CALL_TEST = 'MOUNTAIN_CALL_TEST',
}
