export enum TimerIdentifier {
  SIP_CONNECT_TIMEOUT = 'SIP_CONNECT_TIMEOUT',
  POSITION_INTERVAL = 'POSITION_INTERVAL',
  AUTH_REFRESH_INTERVAL = 'AUTH_REFRESH_INTERVAL',
  SLOWLY_LOADING_TIMEOUT= 'SLOWLY_LOADING_TIMEOUT'
}
